import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight } from 'lucide-react';
import { BottleDrawing } from '@/components/pcc/BottleDrawing';
import { BottleExplorer } from '@/components/pcc/BottleExplorer';
import { HomeHero } from '@/components/pcc/HomeHero';
import { PhotoCTA, SectionTitle } from '@/components/pcc/Site';
import { images, sizes, solutions, industries, work, process } from '@/components/pcc/content';

export const Route = createFileRoute('/')({ head: () => ({ meta: [ { title: 'Pure Custom Creation | Your Brand. Every Table.' }, { name: 'description', content: 'Custom-branded bottled water and hospitality branding for cafés, restaurants, hotels and events in Sri Lanka.' }, { property: 'og:title', content: 'Pure Custom Creation | Your Brand. Every Table.' }, { property: 'og:description', content: 'Premium custom bottled water and hospitality branding, made for your brand in Sri Lanka.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' } ] }), component: Home });
function Home() {
  return <>
    <HomeHero />
    <section id="categories" className="border-b border-border bg-paper"><div className="container-pcc grid grid-cols-2 items-center gap-5 py-7 md:grid-cols-[1.5fr_repeat(4,1fr)] md:py-9"><span className="eyebrow col-span-2 text-primary md:col-span-1">MADE FOR THE PLACES<br />PEOPLE REMEMBER</span>{['Cafés', 'Restaurants', 'Hotels', 'Events'].map((x, i) => <Link to="/industries" key={x} className="group flex items-center justify-between border-l border-border pl-4 text-sm font-bold md:pl-6 md:text-base">{x}<span className="font-mono text-[10px] text-muted-foreground">0{i + 1}</span></Link>)}</div></section>
    <section className="bg-ink py-20 text-primary-foreground md:py-28"><div className="container-pcc"><SectionTitle eyebrow="01 / THE BOTTLE / ENGINEERING" title="THE BOTTLE ENGINEERED FOR YOUR BRAND." light description="A refined canvas for the identity you’ve built." /><div className="grid gap-8 lg:grid-cols-[1fr_1fr]"><div className="technical-grid relative flex min-h-[460px] items-center justify-center border border-line-dark p-6 md:min-h-[600px]"><BottleDrawing /><span className="absolute bottom-5 left-5 font-mono text-[10px] uppercase tracking-widest text-primary-foreground/40">PCC / BOTTLE STUDY / VISUAL REFERENCE</span></div><BottleExplorer /></div><div className="mt-8 border-t border-line-dark pt-7 text-xs text-primary-foreground/55"><p className="max-w-2xl leading-6">Bottle dimensions and technical specifications are confirmed during project scoping so your final production details match the selected bottle and finish.</p></div></div></section>
    <section className="bg-paper py-20 md:py-28"><div className="container-pcc"><div className="flex flex-wrap items-end justify-between gap-6"><SectionTitle eyebrow="02 / THE RANGE" title="THE RIGHT SIZE. THE SAME IMPACT." /><Link to="/custom-water" className="mb-12 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-primary">Explore custom water <ArrowRight size={16} /></Link></div><div className="grid gap-8 lg:grid-cols-[1.2fr_1fr]"><div className="aspect-[4/3] overflow-hidden bg-secondary"><img src={images.range} loading="lazy" width={1536} height={1024} alt="Pure Custom Creation branded bottle visual" className="image-cover" /></div><div className="flex flex-col justify-center">{sizes.map((item, i) => <Link key={item.size} to="/custom-water" className="group grid grid-cols-[minmax(0,1fr)_auto] items-center border-t border-border py-5 last:border-b md:py-7"><div className="min-w-0"><span className="font-mono text-[10px] text-primary">0{i + 1} / SIZE</span><h3 className="display mt-2 text-4xl md:text-5xl">{item.size}</h3><p className="mt-2 text-sm text-muted-foreground">{item.label}</p></div><ArrowRight className="shrink-0 transition-transform group-hover:translate-x-1" /></Link>)}</div></div></div></section>
    <section className="border-t border-border bg-background py-20 md:py-28"><div className="container-pcc"><SectionTitle eyebrow="03 / MORE THAN WATER" title="EVERY DETAIL, ON BRAND." /><div className="grid gap-4 md:grid-cols-3">{solutions.slice(0,3).map((item, i) => <Link key={item.title} to="/solutions" className="group block"><div className="aspect-[4/5] overflow-hidden bg-secondary"><img src={item.image} loading="lazy" width={1536} height={1024} alt={`${item.title} presentation`} className="image-cover image-zoom" /></div><div className="flex items-start justify-between border-b border-border py-5"><div><span className="font-mono text-[10px] text-primary">0{i + 1} / SOLUTION</span><h3 className="mt-2 font-display text-xl font-bold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.detail}</p></div><ArrowRight size={18} /></div></Link>)}</div><Link to="/solutions" className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-primary">All solutions <ArrowRight size={16} /></Link></div></section>
    <section className="bg-ink-soft py-20 text-primary-foreground md:py-28"><div className="container-pcc"><SectionTitle eyebrow="04 / WHERE WE BELONG" title="MADE FOR HOSPITALITY." light /><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-4">{industries.map((item, i) => <Link to="/industries" key={item.title} className="group relative aspect-[3/4] overflow-hidden bg-ink"><img src={item.image} loading="lazy" width={1536} height={1024} alt={`${item.title} hospitality setting`} className="image-cover image-zoom opacity-65" /><div className="absolute inset-0 bg-gradient-to-t from-ink/85 to-transparent" /><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between"><div><span className="font-mono text-[10px] text-red-soft">0{i + 1}</span><h3 className="mt-2 font-display text-xl font-bold md:text-2xl">{item.title}</h3></div><ArrowRight size={18} /></div></Link>)}</div></div></section>
    <section className="bg-paper py-20 md:py-28"><div className="container-pcc"><div className="flex flex-wrap items-end justify-between gap-5"><SectionTitle eyebrow="05 / BRAND APPLICATIONS" title="YOUR BRAND IN ITS ELEMENT." /><Link to="/our-work" className="mb-12 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-primary">View our work <ArrowRight size={16} /></Link></div><div className="grid gap-4 md:grid-cols-2">{work.slice(0,2).map((item,i) => <Link to="/our-work" key={item.title} className="group"><div className="aspect-[4/3] overflow-hidden bg-secondary"><img src={item.image} loading="lazy" width={1536} height={1024} alt={`${item.title} branded hospitality setting`} className="image-cover image-zoom" /></div><div className="flex justify-between border-b border-border py-5"><div><span className="font-mono text-[10px] text-primary">0{i + 1} / BRAND APPLICATION</span><h3 className="mt-2 font-display text-2xl font-bold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.type}</p></div><ArrowRight size={18} /></div></Link>)}</div></div></section>
    <section className="border-t border-border bg-background py-20 md:py-28"><div className="container-pcc"><SectionTitle eyebrow="06 / THE PROCESS" title="SIMPLE FROM START TO FINISH." /><div className="grid border-t border-border md:grid-cols-4">{process.map(([number,title,detail]) => <div key={number} className="border-b border-border py-7 md:border-r md:px-6 first:md:pl-0 last:md:border-r-0"><span className="font-mono text-3xl text-primary">{number}</span><h3 className="mt-10 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{detail}</p></div>)}</div><Link to="/how-it-works" className="mt-9 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-primary">How it works <ArrowRight size={16} /></Link></div></section>
    <PhotoCTA />
  </>;
}